### PR TITLE
Add Tweet Form HTML Markup

### PR DESCRIPTION
**Pull request by AlexEntrepreneur**

### CODE REVIEW

**Comment by AlexEntrepreneur** [comment]
[Implement Tweet Form Component](https://trello.com/c/1hiYwkVH/25-implement-tweet-form-component)

**Review by niklasbec — APPROVED** [review]
Looks good!

**Comment by AlexEntrepreneur** [comment]
[Some feature](https://trello.com/c/W7qm8OFk/27-some-feature)

**Comment by AlexEntrepreneur** [comment]
[Create "Send Tweet" Form](https://trello.com/c/rPcXfuUP/28-create-send-tweet-form)

**Pull request merged**
